workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter create --org com.gymapp \
            --project-name workout_app /tmp/app
          cp lib/main.dart /tmp/app/lib/main.dart
          cp pubspec.yaml /tmp/app/pubspec.yaml
          cd /tmp/app
          flutter pub get
          flutter build apk --debug
    artifacts:
      - /tmp/app/build/app/outputs/flutter-apk/app-debug.apk
